version: '3.3'
services:
  xml-xsd-validator:
    build: ./
    image: artyomov/xml-xsd-validator:latest
    ports:
    - '18080:8080'
    - '18000:8000'
    environment:
      REFERENCE_XSD_PATH: /xsd/OTA_VehAvailRateRS.xsd
    volumes:
    - ./xsd:/xsd